#!/usr/bin/env python

# Copyright 2016 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import io
import os
import sys
import unittest

import verify_boilerplate

class TestBoilerplate(unittest.TestCase):

  def setUp(self):
    self.old_cwd = os.getcwd()
    if os.getenv('TEST_WORKSPACE'): # Running in bazel
      os.chdir('verify/boilerplate')
    os.chdir('test/')
    self.old_out = sys.stdout
    sys.stdout = io.StringIO()

  def tearDown(self):
    sys.stdout = self.old_out
    os.chdir(self.old_cwd)

  def test_boilerplate(self):

    class Args(object):
      def __init__(self):
        self.filenames = []
        self.rootdir = '.'
        self.boilerplate_dir = '../'
        self.skip = []
        self.verbose = True

    verify_boilerplate.ARGS = Args()
    with self.assertRaises(SystemExit):
        verify_boilerplate.main()

    output = sys.stdout.getvalue()
    expected = '\n'.join(verify_boilerplate.nonconforming_lines([
        './fail.go',
        './fail.py',
        './fail_2026.go',
    ])) + '\n' # add trailing newline

    self.assertEqual(output, expected)

  def test_is_generated(self):
    # Files with the standard "Code generated ... DO NOT EDIT." marker are
    # considered generated and must not be checked for copyright boilerplate.
    self.assertTrue(verify_boilerplate.is_generated(
        "// Code generated by some-tool. DO NOT EDIT.\n\npackage test\n"))
    self.assertTrue(verify_boilerplate.is_generated(
        "package test\n\n// Code generated by protoc. DO NOT EDIT.\n"))
    # Ordinary files are not generated.
    self.assertFalse(verify_boilerplate.is_generated(
        "package test\n"))
    self.assertFalse(verify_boilerplate.is_generated(
        "// some-tool generated this. DO NOT EDIT.\n"))

  def test_generated_file_skips_boilerplate(self):
    # A generated file with no copyright header must still pass.
    class Args(object):
      def __init__(self):
        self.filenames = []
        self.rootdir = '.'
        self.boilerplate_dir = '../'
        self.skip = []
        self.verbose = True

    verify_boilerplate.ARGS = Args()
    regexs = verify_boilerplate.get_regexs()
    refs = verify_boilerplate.get_refs()
    self.assertTrue(
        verify_boilerplate.file_passes('generated.go', refs, regexs))


if __name__ == '__main__':
    unittest.main()
